create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  project_year integer not null check (project_year between 1900 and 2100),
  position integer not null unique check (position > 0),
  image_url text,
  accent_class text not null default 'project-one',
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 120),
  email text not null check (char_length(email) <= 254),
  message text not null check (char_length(message) between 10 and 3000),
  created_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.inquiries enable row level security;
create policy "Published projects are publicly readable" on public.projects for select using (published = true);
create policy "Visitors can send an inquiry" on public.inquiries for insert with check (true);

insert into public.projects (title, category, project_year, position, accent_class)
values ('Harbor House', 'Residential', 2024, 1, 'project-one'), ('The Atrium', 'Workplace', 2023, 2, 'project-two'), ('Desert Courtyard', 'Hospitality', 2022, 3, 'project-three')
on conflict (position) do nothing;
