-- CMS Schema Extension for Bilingual Portfolio
-- Migration 001: New tables, RLS policies, storage buckets

-- ============================================================
-- Drop old tables (fresh start for CMS)
-- ============================================================
DROP TABLE IF EXISTS public.inquiries CASCADE;
DROP TABLE IF EXISTS public.project_images CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.contact_messages CASCADE;
DROP TABLE IF EXISTS public.site_settings CASCADE;
DROP TABLE IF EXISTS public.contact_page_settings CASCADE;

-- ============================================================
-- site_settings (singleton)
-- ============================================================
CREATE TABLE public.site_settings (
  id int PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  profile_image_url text,
  about_en text NOT NULL DEFAULT '',
  about_ar text NOT NULL DEFAULT '',
  footer_copy_en text NOT NULL DEFAULT '',
  footer_copy_ar text NOT NULL DEFAULT '',
  footer_email text NOT NULL DEFAULT '',
  footer_social_github text,
  footer_social_linkedin text,
  footer_social_instagram text,
  color_tokens jsonb NOT NULL DEFAULT '{
    "background": "#edece6",
    "surface": "#d8d4c9",
    "textPrimary": "#1d211e",
    "textMuted": "#5d625d",
    "accent": "#bc4e32",
    "border": "rgba(29, 33, 30, 0.2)",
    "danger": "#9b3925"
  }',
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.site_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- contact_page_settings (singleton)
-- ============================================================
CREATE TABLE public.contact_page_settings (
  id int PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  heading_en text NOT NULL DEFAULT 'Contact Me',
  heading_ar text NOT NULL DEFAULT 'تواصل معي',
  intro_en text NOT NULL DEFAULT '',
  intro_ar text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  location_en text NOT NULL DEFAULT '',
  location_ar text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.contact_page_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- projects (bilingual)
-- ============================================================
CREATE TABLE public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_en text NOT NULL,
  title_ar text NOT NULL,
  description_en text NOT NULL DEFAULT '',
  description_ar text NOT NULL DEFAULT '',
  category text NOT NULL,
  location text,
  year int CHECK (year BETWEEN 1900 AND 2100),
  cover_image_url text,
  featured_position int UNIQUE CHECK (featured_position BETWEEN 1 AND 3),
  published boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- project_images (gallery)
-- ============================================================
CREATE TABLE public.project_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  image_url text NOT NULL,
  alt_en text NOT NULL DEFAULT '',
  alt_ar text NOT NULL DEFAULT '',
  display_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_project_images_project_id ON public.project_images(project_id);
CREATE INDEX idx_project_images_order ON public.project_images(project_id, display_order);

-- ============================================================
-- contact_messages
-- ============================================================
CREATE TABLE public.contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_name text NOT NULL CHECK (char_length(sender_name) BETWEEN 2 AND 120),
  sender_email text NOT NULL CHECK (char_length(sender_email) <= 254),
  message text NOT NULL CHECK (char_length(message) BETWEEN 10 AND 3000),
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- Row Level Security (tables are fresh, no existing policies)
-- ============================================================

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read site settings" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Admin can update site settings" ON public.site_settings FOR UPDATE USING (auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');

ALTER TABLE public.contact_page_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read contact settings" ON public.contact_page_settings FOR SELECT USING (true);
CREATE POLICY "Admin can update contact settings" ON public.contact_page_settings FOR UPDATE USING (auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read published projects" ON public.projects FOR SELECT USING (published = true);
CREATE POLICY "Admin can do everything with projects" ON public.projects FOR ALL USING (auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');

ALTER TABLE public.project_images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read images for published projects" ON public.project_images FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.projects WHERE id = project_id AND published = true)
);
CREATE POLICY "Admin can do everything with project images" ON public.project_images FOR ALL USING (auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can submit contact messages" ON public.contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin can read contact messages" ON public.contact_messages FOR SELECT USING (auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');
CREATE POLICY "Admin can update contact messages" ON public.contact_messages FOR UPDATE USING (auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');
CREATE POLICY "Admin can delete contact messages" ON public.contact_messages FOR DELETE USING (auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');

-- ============================================================
-- Storage Buckets
-- ============================================================
INSERT INTO storage.buckets (id, name, public) VALUES ('profile', 'profile', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('projects', 'projects', true) ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public can view profile images" ON storage.objects FOR SELECT USING (bucket_id = 'profile');
CREATE POLICY "Admin can upload profile images" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'profile' AND auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');
CREATE POLICY "Admin can delete profile images" ON storage.objects FOR DELETE USING (bucket_id = 'profile' AND auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');

CREATE POLICY "Public can view project images" ON storage.objects FOR SELECT USING (bucket_id = 'projects');
CREATE POLICY "Admin can upload project images" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'projects' AND auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');
CREATE POLICY "Admin can delete project images" ON storage.objects FOR DELETE USING (bucket_id = 'projects' AND auth.jwt() ->> 'email' = 'ahmed.elkholy6480@gmail.com');
